apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: benchmark-debug
spec:
  selector:
    matchLabels:
      app: benchmark
  replicas: 1
  template:
    metadata:
      labels:
        app: benchmark
      namespace: aea-research
    spec:
      tolerations:
      - key: dedicated
        operator: Equal
        value: agent
        effect: NoSchedule
      # nodeSelector:
      #   type: agent-test
      
      containers:
      # initContainers:
      - name: python
        image: python:3.8-buster
        # command: ['sh', '-c', 'echo "this stuff works!" | tee /data/index.html']
        command: ['sh', '-c', 'bash /app/run_benchmark.sh | tee /data/index.html ; sleep 30000']
        volumeMounts:
        - name: benchmark-data
          mountPath: /data
        - name: benchmark-script
          mountPath: /app

      # containers:
      # - name: benchmark
      #   image: nginx:1.18.0
      #   volumeMounts:
      #   - name: benchmark-data
      #     mountPath: /usr/share/nginx/html
      #   - name: benchmark-script
      #     mountPath: /app
          
      volumes:
      - name: benchmark-data
        persistentVolumeClaim:
          claimName: benchmark-vol
      - name: benchmark-script
        configMap:
          name: run-benchmark

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmark-vol
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi