agent_name: faber
author: ali
version: 0.1.0
description: ''
license: Apache-2.0
aea_version: 0.3.0
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/http_client:0.1.0
- fetchai/stub:0.1.0
- fetchai/webhook:0.1.0
contracts: []
protocols:
- fetchai/default:0.1.0
- fetchai/http:0.1.0
skills:
- ali/demo:0.1.0
- fetchai/error:0.2.0
default_connection: fetchai/http_client:0.1.0
default_ledger: fetchai
ledger_apis: {}
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  ethereum: eth_private_key.txt
  fetchai: fet_private_key.txt
registry_path: ../packages
