name: ml_data_provider
author: fetchai
version: 0.7.0
description: The ml data provider skill implements a provider for Machine Learning
  datasets in order to monetize data.
license: Apache-2.0
aea_version: '>=0.5.0, <0.6.0'
fingerprint:
  __init__.py: QmbQigh7SV7dD2hLTGv3k9tnvpYWN1otG5yjiM7F3bbGEQ
  behaviours.py: QmWgXU9qgahXwMKNqLLfDiGNYJozSXv2SVMkoPDQncC7ok
  dialogues.py: Qmct8ZJie2AtvN3jEJCsJM1LCbcUhaVgD4swKw1FvAFgvt
  handlers.py: QmPmTwojRvD11rpf1twKezvzv5cVSpdwYj81qqTMF89VLm
  strategy.py: QmPDNk4RYGCeGeGyazhzFKgD7X2Y4iQQM5xmuYP4yqkvtt
fingerprint_ignore_patterns: []
contracts: []
protocols:
- fetchai/default:0.3.0
- fetchai/ledger_api:0.1.0
- fetchai/ml_trade:0.3.0
- fetchai/oef_search:0.3.0
skills:
- fetchai/generic_seller:0.8.0
behaviours:
  service_registration:
    args:
      services_interval: 20
    class_name: ServiceRegistrationBehaviour
handlers:
  ledger_api:
    args: {}
    class_name: LedgerApiHandler
  ml_trade:
    args: {}
    class_name: MlTradeHandler
models:
  default_dialogues:
    args: {}
    class_name: DefaultDialogues
  ledger_api_dialogues:
    args: {}
    class_name: LedgerApiDialogues
  ml_trade_dialogues:
    args: {}
    class_name: MlTradeDialogues
  oef_search_dialogues:
    args: {}
    class_name: OefSearchDialogues
  strategy:
    args:
      batch_size: 2
      buyer_tx_fee: 10
      currency_id: FET
      dataset_id: fmnist
      is_ledger_tx: true
      ledger_id: cosmos
      price_per_data_batch: 100
      seller_tx_fee: 0
    class_name: Strategy
dependencies:
  numpy: {}
  tensorflow:
    version: ==1.14.0
