name: 'ml_data_provider'
author: fetchai
version: 0.1.0
license: Apache-2.0
fingerprint:
  __init__.py: QmbQigh7SV7dD2hLTGv3k9tnvpYWN1otG5yjiM7F3bbGEQ
  behaviours.py: QmekDWMQBH6AwBmbf96KEsUqHSokqroaBCT59sYciXiTny
  handlers.py: QmZz1fvKaMirRffiFNMo8ehM31Zr3vRvHnF4JZcMb8iwiq
  strategy.py: QmRPSMeGPzq1W26ppZhXxubfL4h1VT4v8Xecxx5dnLJpoc
description: "The ml data provider skill implements a provider for Machine Learning datasets in order to monetize data."
behaviours:
  service_registration:
    class_name: ServiceRegistrationBehaviour
    args:
      services_interval: 30
handlers:
  ml_trade:
    class_name: MLTradeHandler
    args: {}
models:
  strategy:
    class_name: Strategy
    args:
      price_per_data_batch: 100
      batch_size: 2
      seller_tx_fee: 0
      buyer_tx_fee: 10
      dataset_id: 'fmnist'
      currency_id: 'FET'
      ledger_id: 'fetchai'
      is_ledger_tx: False
protocols: ['fetchai/oef:0.1.0', 'fetchai/ml_trade:0.1.0']
dependencies:
  tensorflow: {}
  numpy: {}
