name: prometheus
author: fetchai
version: 0.2.0
protocol_specification_id: fetchai/prometheus:0.2.0
type: protocol
description: A protocol for adding and updating metrics to a prometheus server.
license: Apache-2.0
aea_version: '>=0.9.0, <0.10.0'
fingerprint:
  README.md: QmVNpxpWSWU8CwVJGxTwrrnsnDKgvih5M33y381xwehCru
  __init__.py: QmQvMGLitiy95SKYYSZQdfUH2UjpZ1ueTJooVuBG19P7QE
  dialogues.py: QmYQYkByWC3sBnQPnDEzFh98ULycx1jzqqs6hLC196YZg5
  message.py: QmTGZhyBzsw9r21qo2gdf2QUZYBiiN33ZSuxGHeRqLUETX
  prometheus.proto: QmbxQuk7qkmW8KXTsSrQRiyPsYfJf1mVBneKfxYrAhR6x6
  prometheus_pb2.py: QmPzYeQxVktLftTadNyXuNJjqi9dwCmnz8K7AVrWo2nqjs
  serialization.py: QmaWVbKwubB4pymQpQQg3yXfjeEdxrehxcHDkb8o4SeXun
fingerprint_ignore_patterns: []
dependencies:
  protobuf: {}
