---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: deployment-name-here 
  namespace: agents-p2p-dht
spec:
  endpoints:
  - dnsName:  agents-p2p-dht.sandbox.fetch-ai.com
    recordTTL: 180
    recordType: CNAME
    targets:
    - fetchpub.sandbox.fetch-ai.com
