site_name: Fetch.AI Developer Documentation
site_url: https://docs.fetch.ai/
site_description: Everything you need to know about Fetch.AI. 
#repo_url: https://github.com/fetchai/docs // commented out to remove edit option
#repo_name: 'GitHub'
site_author: katharine.murphy@fetch.ai


theme:
  name: 'material'
  logo:
    icon: code
  feature:
    tabs: true  



nav:

  - Autonomous Economic Agent Framework:
    - Welcome:
      - "What is the AEA?": 'aea/index.md'
      - "Architecture": 'aea/architecture.md'
      - "Version": 'aea/version.md'
    - AEA quick start: 'aea/quickstart.md'
    - Get developing:
      - "Connection": 'aea/connection.md'
      - "Protocol": 'aea/protocol.md'
      - "Skill": 'aea/skill.md'
      - "Scaffolding": 'aea/scaffolding.md'
      - "CLI commands": 'aea/cli_overview.md'
    - Integration:
      - "Integrate with third parties": 'aea/integration.md'
    - Demos:
      - "AEA gym skill": 'aea/gym-skill.md'
      - "Gym efficiency demo": 'aea/gym-plugin.md'
      - "TAC": 'aea/tac.md'



markdown_extensions:
  - pymdownx.superfences
  - admonition

extra_css:
    - css/my-styles.css
