site_name: Fetch.AI Developer Documentation
site_url: https://docs.fetch.ai/
site_description: Everything you need to know about Fetch.AI. 
#repo_url: https://github.com/fetchai/docs // commented out to remove edit option
#repo_name: 'GitHub'
site_author: diarmid.campbell@fetch.ai


theme:
  name: 'material'
  logo:
    icon: code
  feature:
    tabs: true  



nav:
  - Autonomous Economic Agent Framework:
    - Welcome: 'index.md'
    - Getting started:
      - AEA quick start: 'quickstart.md'
      - AEA and Web Frameworks: 'aea-vs-mvc.md'
      - Build an AEA step by step: 'steps.md'
      - Build a skill for an AEA: 'skill-guide.md'
      - Build an AEA programmatically: 'build-aea-programmatically.md'
      - AEAs vs Agents: 'agent-vs-aea.md'
    - The AEA universe:
      - Agent-oriented development: 'agent-oriented-development.md'
      - Vision: 'vision.md'
      - Application areas: 'app-areas.md'
      - Relation to OEF and Ledger: 'oef-ledger.md'
      - Trust issues: 'trust.md'
      # - "Two-layered machine learning": 'two-layer.md'
    - Demo guides:
      - "Car park agent": 'car-park-skills.md'
      - "Gym example": 'gym-example.md'
      - "Gym skill": 'gym-skill.md'
      - "ML skills": 'ml-skills.md'
      - "TAC skills": 'tac-skills.md'
      - "TAC external app": 'tac.md'
      - "Weather skills": 'weather-skills.md'
      - "Thermometer skills step by step": 'thermometer.md'
    - Architecture:
      - "Design principles": 'design-principles.md'
      - "Architectural diagram": 'diagram.md'
      - "Core components": 'core-components.md'
      - "File structure": 'file-structure.md'
    - Developer guides:
      - Version: 'version.md'
      - "Skill": 'skill.md'
      - "Protocol": 'protocol.md'
      - "Connection": 'connection.md'
      - "Scaffolding packages": 'scaffolding.md'
      - "Generating protocols": 'generator.md'
      - "Logging": 'logging.md'
      - CLI:
         - "CLI tool": 'cli-how-to.md'
         - "Commands": 'cli-commands.md'
         - "GUI": 'cli-gui.md'
         - "Generating wealth": 'wealth.md'
      - "Build an AEA on a Raspberry Pi": 'raspberry-set-up.md'
      - "Integrate with third parties": 'integration.md'


plugins:
    - markdownmermaid

markdown_extensions:
  - pymdownx.superfences
  - admonition

extra_css:
    - css/my-styles.css

extra_javascript:
    - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
