site_name: Fetch.AI Developer Documentation
site_url: https://docs.fetch.ai/
site_description: Everything you need to know about Fetch.AI. 
#repo_url: https://github.com/fetchai/docs // commented out to remove edit option
#repo_name: 'GitHub'
site_author: katharine.murphy@fetch.ai


theme:
  name: 'material'
  logo:
    icon: code
  feature:
    tabs: true  



nav:

  - Autonomous Economic Agent Framework:
    - Welcome:
      - "What is the AEA framework?": 'index.md'
      - "Architecture": 'architecture.md'
      - "Version": 'version.md'
    - AEA quick start: 'quickstart.md'
    - Developer guide:
      - "Step by step": 'steps.md'
      - "Scaffolding": 'scaffolding.md'
      - "Connection": 'connection.md'
      - "Protocol": 'protocol.md'
      - "Skill": 'skill.md'
      - CLI:
         - "CLI tool": 'cli-how-to.md'
         - "Commands": 'cli-commands.md'
    - Integration:
      - "Integrate with third parties": 'integration.md'
    - Demos:
      - "AEA gym skill": 'gym-skill.md'
      - "Gym efficiency demo": 'gym-plugin.md'
      - "TAC skill": 'tac-skill.md'
      - "Transport app skill": 'transport.md'
      - "Buy/sell game skill": 'buy-sell.md'
      - "TAC external app": 'tac.md'



markdown_extensions:
  - pymdownx.superfences
  - admonition

extra_css:
    - css/my-styles.css
