site_name: Fetch.AI Developer Documentation
site_url: https://docs.fetch.ai/
site_description: Everything you need to know about Fetch.AI. 
#repo_url: https://github.com/fetchai/docs // commented out to remove edit option
#repo_name: 'GitHub'
site_author: katharine.murphy@fetch.ai


theme:
  name: 'material'
  logo:
    icon: code
  feature:
    tabs: true  



nav:

  - Autonomous Economic Agent Framework:
    - Welcome: 'index.md'
    - AEA quick start: 'quickstart.md'
    - The AEA universe:
      - "Vision": 'vision.md'
      - "Application areas": 'app-areas.md'
      - "Relation to OEF and Ledger": 'oef-ledger.md'
      - "Trust issues": 'trust.md'
      # - "Two-layered machine learning": 'two-layer.md'
    - Demos:
      - "Gym demo": 'gym-plugin.md'
      - "Gym skill": 'gym-skill.md'
      - "Weather skills": 'weather-skills.md'
      - "TAC external app": 'tac.md'
      # - "FIPA skill": 'fipa-skill.md'
      # - "TAC skill": 'tac-skill.md'
      - "Car park agent": 'car-park.md'
    - Architecture:
      - "Design principles": 'design-principles.md'
      - "Architectural diagram": 'diagram.md'
      - "Core components": 'core-components.md'
      - "File structure": 'file-structure.md'
    - Developer guide:
      - "Step by step": 'steps.md'
      - "Skill": 'skill.md'
      - "Build your own skill": 'skill-guide.md'
      - "Protocol": 'protocol.md'
      - "Connection": 'connection.md'
      - "Scaffolding": 'scaffolding.md'
      - "Logging": 'logging.md'
      - CLI:
         - "CLI tool": 'cli-how-to.md'
         - "Commands": 'cli-commands.md'
         - "GUI": 'cli-gui.md'
      - "Code an agent directly": 'hacking-an-agent.md'
      - "Integrate with third parties": 'integration.md'





markdown_extensions:
  - pymdownx.superfences
  - admonition

extra_css:
    - css/my-styles.css
