aea_version: 0.2.2
agent_name: m_participant_1
author: default_author
connections:
- fetchai/oef:0.1.0
- fetchai/stub:0.1.0
contracts:
- fetchai/erc1155:0.1.0
default_connection: fetchai/stub:0.1.0
default_ledger: ethereum
description: ''
fingerprint: {}
ledger_apis:
  ethereum:
    address: https://ropsten.infura.io/v3/f00f7b3ba0e848ddbdc8941c527447fe
    chain_id: 3
    gas_price: 50
license: Apache-2.0
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  ethereum: eth_private_key.txt
  fetchai: fet_private_key.txt
protocols:
- fetchai/default:0.1.0
- fetchai/fipa:0.1.0
- fetchai/oef:0.1.0
- fetchai/tac:0.1.0
registry_path: ../packages
skills:
- fetchai/error:0.1.0
- fetchai/tac_negotiation:0.1.0
- fetchai/tac_participation:0.1.0
version: 0.1.0
