aea_version: 0.1.5
agent_name: some_agent
authors: ''
connections:
- local
- oef
default_connection: oef
license: ''
private_key_pem_path: ''
protocols:
- default
- fipa
- oef
registry_path: ../packages
skills:
- error
- fipa_negotiation
url: ''
version: v1
