aea_version: 0.1.5
agent_name: Test3
authors: ''
connections:
- oef
default_connection: oef
license: ''
private_key_pem_path: ''
protocols:
- default
- tac
registry_path: ../packages
skills:
- echo
- error
url: ''
version: v1
