aea_version: 0.1.15
agent_name: tac_controller
author: ''
connections:
- oef
- stub
default_connection: stub
default_ledger: ethereum
description: ''
fingerprint: ''
ledger_apis:
- ledger_api:
    addr: https://ropsten.infura.io/v3/f00f7b3ba0e848ddbdc8941c527447fe
    ledger: ethereum
    port: 3
license: ''
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
- private_key_path:
    ledger: default
    path: default_private_key.pem
- private_key_path:
    ledger: fetchai
    path: fet_private_key.txt
- private_key_path:
    ledger: ethereum
    path: eth_private_key.txt
protocols:
- default
- fipa
- oef
- tac
registry_path: ../packages
skills:
- error
- tac_control
url: ''
version: v1
