agent_name: tac_controller
author: fetchai
version: 0.19.0
description: An AEA to manage an instance of the TAC (trading agent competition)
license: Apache-2.0
aea_version: '>=0.10.0, <0.11.0'
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/p2p_libp2p:0.15.0
- fetchai/soef:0.16.0
contracts:
- fetchai/erc1155:0.16.0
protocols:
- fetchai/default:0.12.0
- fetchai/oef_search:0.13.0
- fetchai/signing:0.10.0
- fetchai/state_update:0.10.0
- fetchai/tac:0.13.0
skills:
- fetchai/tac_control:0.16.0
default_connection: fetchai/p2p_libp2p:0.15.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  fetchai: fetchai_private_key.txt
registry_path: ../packages
default_routing:
  fetchai/oef_search:0.13.0: fetchai/soef:0.16.0
connection_private_key_paths:
  fetchai: fetchai_connection_private_key.txt
---
public_id: fetchai/p2p_libp2p:0.15.0
type: connection
config:
  delegate_uri: null
  entry_peers:
  - /dns4/acn.fetch.ai/tcp/9001/p2p/16Uiu2HAmVWnopQAqq4pniYLw44VRvYxBUoRHqjz1Hh2SoCyjbyRW
  local_uri: 127.0.0.1:10000
  public_uri: null
---
public_id: fetchai/tac_control:0.16.0
type: skill
models:
  parameters:
    args:
      service_data:
        key: tac
        value: v1_1
      registration_start_time: 12 02 2021 09:10
