aea_version: 0.1.13
agent_name: Diarmid_agent
authors: ''
connections:
- oef
default_connection: oef
description: ''
ledger_apis: []
license: ''
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: []
protocols:
- default
registry_path: ../packages
skills:
- echo
- error
url: ''
version: v1
