swagger: "2.0"
info:
  description: This is the swagger file that goes with our server code
  version: "1.0.0"
  title: Swagger Rest Article
consumes:
  - application/json
produces:
  - application/json

basePath: /api

# Paths supported by the server application
paths:
  /agent:
    get:
      operationId: app.get_agents
      tags:
      - agents
      summary: Return list of all aea projects
      description: List of local folders under the user name (which correspond to aea projects)
      responses:
        200:
          description: Successfully read agent list operation
          schema:
            type: array
            items:
              type: string
    post:
      operationId: app.create_agent
      tags:
        - People
      summary: Create a person and add it to the people list
      description: Create a new person in the people list
      parameters:
        - name: agent_id
          in: body
          description: Person to create
          required: True
          schema:
            type: string

      responses:
        201:
          description: Successfully created person in list

        400:
          description: Cannot create agent
          schema:
            type: string

  /agent/{agent_id}:
    delete:
      operationId: app.delete_agent
      tags:
      - agents
      summary: Delete an aea project
      parameters:
        - name: agent_id
          in: path
          description: id of agent to delete
          type: string
          required: True
      responses:
        201:
          description: Agent deleted successfully
          schema:
            type: string

        400:
          description: Cannot delete agent
          schema:
            type: string

  /agent/{agent_id}/{item_type}:
    post:
      operationId: app.fetch_item
      tags:
      - agents
      summary: Fetch a protocol from the registry to the currently selected agent
      parameters:
        - name: agent_id
          in: path
          description: id of agent to add protocol to
          type: string
          required: True
        - name: item_type
          in: path
          description: type of item to add ("protocol", "connection" or "skill")
          type: string
          required: True
        - name: item_id
          in: body
          description: id of protocol to add
          schema:
            type: string
          required: True
      responses:
        201:
          description: Protocol added successfully
          schema:
            type: string

        400:
          description: Cannot add protocol to agent
          schema:
            type: string
    get:
      operationId: app.get_local_items
      tags:
      - agents
      summary: Return list of all items if a given type supported by this agent
      parameters:
        - name: agent_id
          in: path
          description: id of agent to searh in
          type: string
          required: True
        - name: item_type
          in: path
          description: type of item to list ("protocol", "connection" or "skill")
          type: string
          required: True

      responses:
        200:
          description: Successfully read protocol list operation
          schema:
            type: array
            items:
              type: string
        400:
          description: Cannot find protocols in agent
          schema:
            type: string

  /agent/{agent_id}/{item_type}/{item_id}:
    delete:
      operationId: app.remove_local_item
      tags:
      - agents
      summary: Delete an protocoo, connectionor skill from an agent
      parameters:
        - name: agent_id
          in: path
          description: id of agent to delete
          type: string
          required: True
        - name: item_type
          in: path
          description: type of item to remove
          type: string
          required: True
        - name: item_id
          in: path
          description: item id to delete
          type: string
          required: True

      responses:
        201:
          description: Agent deleted successfully
          schema:
            type: string

        400:
          description: Cannot delete agent
          schema:
            type: string

  /protocol:
    get:
      operationId: app.get_registered_protocols
      tags:
      - agents
      summary: Return list of all registered protocols
      description: List of folders under the packages protocols directory
      responses:
        200:
          description: Successfully read protocol list operation
          schema:
            type: array
            items:
              type: string

  /connection:
    get:
      operationId: app.get_registered_connections
      tags:
      - agents
      summary: Return list of all registered connections
      description: List of local folders under the packages connections directory
      responses:
        200:
          description: Successfully read connection list operation
          schema:
            type: array
            items:
              type: string

  /skill:
    get:
      operationId: app.get_registered_skills
      tags:
      - agents
      summary: Return list of all registered kills
      description: List of local folders under the packages connections directory
      responses:
        200:
          description: Successfully read skills list operation
          schema:
            type: array
            items:
              type: string

