aea_version: 0.1.15
agent_name: car_detector
author: fetchai
connections:
- fetchai/oef:0.1.0
- fetchai/stub:0.1.0
default_connection: fetchai/stub:0.1.0
default_ledger: fetchai
description: ''
fingerprint: ''
ledger_apis: {}
license: ''
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: []
protocols:
- fetchai/default:0.1.0
- fetchai/fipa:0.1.0
- fetchai/oef:0.1.0
registry_path: ../packages
skills:
- fetchai/carpark_detection:0.1.0
- fetchai/error:0.1.0
url: ''
version: 0.1.0
