name: default_test
author: fetchai
version: 0.1.0
license: Apache-2.0
description: 'A protocol for exchanging any bytes message.'
speech_acts:
  bytes:
    content: pt:bytes
  error:
    error_code: ct:ErrorCode
    error_msg: pt:str
    error_data: pt:dict[pt:str, ct:ErrorData]
---
ct:ErrorCode: |
  enum ErrorCodeEnum {
      UNSUPPORTED_PROTOCOL = -10001;
      DECODING_ERROR = -10002;
      INVALID_MESSAGE = -10003;
      UNSUPPORTED_SKILL = -10004;
      INVALID_DIALOGUE = -10005;
    }
  ErrorCodeEnum error_code = 1;
ct:ErrorData: |
  bytes error_data = 1;
