name: default
author: fetchai
version: 0.1.0
license: Apache 2.0
description: 'A protocol for exchanging any bytes message.'
speech_acts:
  bytes:
    content: bytes
  error:
    error_code: ErrorCode
    error_msg: str
    error_data: dict
