aea_version: 0.2.4
agent_name: m_agent
author: aris
connections:
- fetchai/oef:0.2.0
- fetchai/stub:0.1.0
contracts: []
default_connection: fetchai/oef:0.2.0
default_ledger: fetchai
description: ''
fingerprint: {}
fingerprint_ignore_patterns: []
ledger_apis: {}
license: Apache-2.0
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths:
  ethereum: eth_private_key.txt
  fetchai: fet_private_key.txt
protocols:
- fetchai/default:0.1.0
- fetchai/fipa:0.1.0
- fetchai/oef_search:0.1.0
- fetchai/rail_stomp:0.1.0
registry_path: ../packages
skills:
- aris/rail_receiver:0.1.0
- fetchai/error:0.1.0
version: 0.1.0
