aea_version: 0.1.6
agent_name: Diarmid2
authors: ''
connections:
- oef
default_connection: oef
description: ''
license: ''
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_pem_path: ''
protocols:
- and
- andasd
- asdasd
- default
registry_path: ../packages
skills:
- error
url: ''
version: v1
