openapi: "3.0.0"
name: coin_price_api
author: fetchai
version: 0.1.0
servers:
  - url: ''
paths:
  /price:
    get:
      summary: List of all coin prices
      operationId: listPrices
      responses:
        '200':
          description: A JSON array of coin prices
          content:
            application/json:
              schema:
                type: array
                items: string
        '404':
          description: The specified coin was not found.
        default:
          description: Unexpected error