openapi: "3.0.0"
name: coin_price_api
author: fetchai
version: 0.1.0
title: Coin price API
servers:
  - url: ''
paths:
  /price:
    get:
      summary: Coin price
      operationId: price
      responses:
        '200':
          description: A JSON response including the coin price
          content:
            application/json:
              schema:
                type: string
        '404':
          description: The coin price was not found.
        default:
          description: Unexpected error