aea_version: 0.1.6
agent_name: my_test
authors: ''
connections:
- oef
default_connection: oef
license: ''
private_key_pem_path: ''
protocols:
- default
- fipa
registry_path: ../packages
skills:
- error
- weather_station
url: ''
version: v1
