aea_version: 0.1.6
agent_name: Diarmid
authors: ''
connections:
- oef
- test
default_connection: oef
license: ''
private_key_pem_path: ''
protocols:
- default
registry_path: ../packages
skills:
- error
url: ''
version: v1
