aea_version: 0.1.6
agent_name: Diarmid
authors: ''
connections:
- gym
default_connection: oef
license: ''
private_key_pem_path: ''
protocols:
- default
- fipa
- gym
- oef
registry_path: ../packages
skills:
- error
- weather_client
url: ''
version: v1
