agent_name: agent
author: ali
version: 0.1.0
description: ''
license: Apache-2.0
aea_version: 0.6.1
fingerprint: {}
fingerprint_ignore_patterns: []
connections:
- fetchai/stub:0.9.0
contracts: []
protocols:
- fetchai/default:0.5.0
skills:
- fetchai/error:0.5.0
default_connection: fetchai/stub:0.9.0
default_ledger: fetchai
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_paths: {}
registry_path: ../packages
