aea_version: 0.1.6
agent_name: AnotherAgnet
authors: ''
connections:
- oef
default_connection: oef
description: ''
license: ''
logging_config:
  disable_existing_loggers: false
  version: 1
private_key_pem_path: ''
protocols:
- default
- fipa
- oef
registry_path: ../packages
skills:
- error
- fipa_negotiation
- weather_client
url: ''
version: v1
