name: AEA framework sanity checks and tests

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  common_checks:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: 3.6
      - uses: actions/setup-go@master
        with:
          go-version: '^1.14.0'
      - name: Golang code style check
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.26
          working-directory: packages/fetchai/connections/p2p_libp2p/
