name: Example workflow for Codecov
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
#        os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install pipenv
        pip install tox
    - name: Security Check - Main
      run: tox -e bandit-main
    - name: Security Check - Tests
      run: tox -e bandit-tests
    - name: Code style check
      run: |
        tox -e black-check
        tox -e flake8
    - name: Static type check
      run: tox -e mypy
    - name: Unit tests and coverage
      run: |
        tox -e py${{ matrix.python-version }} -- --no-integration-tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: true

